# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 全民悦动

on:
  workflow_dispatch:
  schedule:
     - cron: '0,30 0-23 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        QMYD_qmydTOKEN: ${{ secrets.QMYD_qmydTOKEN }}
        QMYD_CASH: ${{ secrets.QMYD_CASH }}
        
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/banditlives/zzymg.git ~/zzymg
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.QMYD_qmydTOKEN
        run: |
          cd ~/zzymg
          git checkout master
          npm install
      - name: '运行 【全民悦动】'
        if: env.QMYD_qmydTOKEN
        run: |
          cd ~/zzymg
          node Task/qmyd.js
        env:
          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
